---
title: "Safety vs Risk"
author: "Mahbub R Maulaa"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#Load libraries
mainlib <- c("tidyverse", "dplyr", "sf", "ggplot2")
lapply(mainlib, library, character.only = TRUE)

#Load datasets
thaiRisk <- read.csv("~/GitHub/RoadPulse2/Risk_Score/final_risk_scores_thailand.csv")
indiaRisk <- read.csv("~/GitHub/RoadPulse2/Risk_Score/final_risk_scores_maharashtra.csv")
thaiVar <- read.csv("~/GitHub/RoadPulse2/Risk_Score/variables_thailand.csv")
indiaVar <- read.csv("~/GitHub/RoadPulse2/Risk_Score/variables_maharashtra.csv")
thaiRoad <- read.csv("~/GitHub/RoadPulse2/data/thai_clean_gdf.csv")
indiaRoad <- read.csv("~/GitHub/RoadPulse2/data/india_clean_gdf.csv")
thaiSafety <- read.csv("~/GitHub/RoadPulse2/data/thai_safety_score.csv")
indiaSafety <- read.csv("~/GitHub/RoadPulse2/data/india_safety_score.csv")
```
```{r}
thaiVar2 <- left_join(thaiVar, thaiRisk, by = "OBJECTID")
indiaVar2 <- left_join(indiaVar, thaiRisk, by = "OBJECTID")
```

```{r  fig.height=10, fig.width=15}
thaiVar2 |>
  filter(SpeedLimit > 0) |>
  ggplot(aes(x = RoadClass, y = F85thPercentileSpeed, color = RoadClass, size = PercentOverLimit)) +
  geom_point(alpha = 0.5) +
  geom_hline(aes(yintercept = SpeedLimit), linetype = "dashed", color = "grey40") +
  scale_size_continuous(range = c(2, 12)) +
  facet_wrap(~SpeedLimit) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r fig.height=10, fig.width=15}
thaiVar2 |>
  filter(SpeedLimit > 0) |>
  ggplot(aes(x = RoadClass, y = F85thPercentileSpeed, color = RoadClass, size = image_risk_score)) +
  geom_point(alpha = 0.5) +
  geom_hline(aes(yintercept = SpeedLimit), linetype = "dashed", color = "grey40") +
  scale_size_continuous(range = c(2, 12)) +
  facet_wrap(~SpeedLimit) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r fig.height=10, fig.width=15}
head(thaiSafety)

thaiSafety |>
  filter(SpeedLimit > 0) |>
  ggplot(aes(x = SpeedSafetyScore, fill = RoadClass)) +
  geom_histogram(stat = "bin") +
  facet_wrap(~SpeedLimit) +
  theme_minimal()
```
```{r}
thaiSafety |>
  filter(SpeedLimit > 0) |>
  split(~ SpeedLimit) |>
  lapply(function(sub_data) {
    current_limit <- unique(sub_data$SpeedLimit)
    
    p <- ggplot(sub_data, aes(x = SpeedSafetyScore, fill = RoadClass)) +
      geom_histogram(bins = 30, alpha = 0.7, position = "stack") +
      theme_minimal() +
      labs(
        title = paste("Speed Safety Score for Speed Limit:", current_limit),
        x = "Speed Safety Score",
        y = "Count"
      )
    
    print(p) # This forces R to render the graph immediately
  }) |> 
  invisible() # Keeps your console clean by hiding the empty list output
```

```{r}
thaiSafety |>
  filter(SpeedLimit > 0) |>
  split(~ RoadClass) |>
  lapply(function(sub_data) {
    current_class <- unique(sub_data$RoadClass)
    
    p <- ggplot(sub_data, aes(x = SpeedSafetyScore, fill = factor(SpeedLimit))) +
      geom_histogram(bins = 30, alpha = 0.7, position = "stack") +
      theme_minimal() +
      labs(
        title = paste("Speed Safety Score for Road Class:", current_class),
        x = "Speed Safety Score",
        y = "Count"
      )
    
    print(p) # This forces R to render the graph immediately
  }) |> 
  invisible() # Keeps your console clean by hiding the empty list output
```

```{r}
thaiSafety |>
  filter(SpeedLimit > 0 & PriorityTier == "High") |>
  split(~ RoadClass) |>
  lapply(function(sub_data) {
    current_class <- unique(sub_data$RoadClass)
    
    p <- ggplot(sub_data, aes(x = SpeedSafetyScore, fill = factor(SpeedLimit))) +
      geom_histogram(bins = 30, alpha = 0.7, position = "stack") +
      theme_minimal() +
      labs(
        title = paste("Speed Safety Score for Road Class:", current_class),
        x = "Speed Safety Score",
        y = "Count"
      )
    
    print(p) # This forces R to render the graph immediately
  }) |> 
  invisible() # Keeps your console clean by hiding the empty list output
```

```{r}
thaiVarinclude <- thaiVar |>
  select(
    
#identity
    "OBJECTID",
    
#positive    
    "vlm_population_density_score",
    "yolo_total_vehicles",
    "vlm_footpath_score",
    "vlm_lane_marking_quality",
    "yolo_total_pedestrians",
    "vlm_road_condition_score",
    "yolo_total_bicycles",

# negatives
    "vlm_lane_count",
    # "vlm_curvature_visible",
    "vlm_intersection_visible",
    "yolo_total_motorcycles"
    # "vlm_overall_walkability"
    # "vlm_building_density_score"
)

thaiAll <- thaiSafety |>
  left_join(thaiVarinclude, by = "OBJECTID") |>
  left_join(thaiRisk, by = "OBJECTID")
```

```{r fig.height=10, fig.width=15}
thaiAll |>
  ggplot(aes(x = SpeedSafetyScore, y = image_risk_score, size = vlm_population_density_score, color = RoadClass)) + 
  geom_point(alpha = 0.4) +
  facet_wrap(~RoadClass) +
  theme_minimal()
```

```{r fig.height=10, fig.width=15}
thaiAll |>
  ggplot(aes(x = SpeedSafetyScore, y = image_risk_score, size = vlm_footpath_score, color = RoadClass)) + 
  geom_point(alpha = 0.4) +
  facet_wrap(~RoadClass) +
  theme_minimal()
```
